/*

    LDR_Light_Sensor_LCD_serial
    
  This program  will read from one ADC channel an analog value or voltage generated by a potential divider made by a 3.3 K resistor and a LDR.
  One end of 3.3K resistor is connected to 5V and other end to LDR (value 200 ohms to 200k ohms). LDr's other end is conneted to ground. 
  When there is no or negligible light on LDR, the LDR resistance is very high and the voltage across LDR or at middle point will be closer to 5V. 
  When there is large amount of light falling on LDR, LDR resistance is low and the voltage across LDR will be low, closer to zero V.  
 
  The program display ADC count and absolute value of voltage on LCD and Serial Port both.    A delay of about 1 second is given between two 
  readings so that data can be viewed easily on Serial.


 The circuit:
 * LCD RS pin to digital pin 13
 * LCD Enable pin to digital pin 12
 * LCD D4 pin to digital pin 5
 * LCD D5 pin to digital pin 4
 * LCD D6 pin to digital pin 3
 * LCD D7 pin to digital pin 2
 * Connect Arduino +5V and Ground pins to General Purpose Input / Output Board +5V and GND pins. Use red wire for +5v and black or green wire for GND.
 * Connect LM35 pin to analog input 0. Do not connect it to digital pin 0. 
 
 Suggested improvement:
   1. Instead of reading one value every 1 second and using it, it may be better to read 10 values spread evenly over 0.1 seconds and taking an average 
   of it and using the average. What do we gain from it. 
   2. Can we extend the number of samples from 10 to 100 in a second?
 
 
   created by P. W Dandekar on 24th May 2010.
   modified on sept 28, 2015
 
 */

// include the library code:
#include <LiquidCrystal.h>

// initialize the library with the numbers of the interface pins
LiquidCrystal lcd(13, 12, 5, 4, 3, 2);

int ilight; // define variables for ADC count, actual voltage measured in mV 
float flight;
int light_sensor_Pin = 0;

void setup() {
  // set up the LCD's number of rows and columns: 
  lcd.begin(16, 2);
  // Print a message to the LCD.
  lcd.print("LightSensor LDR");// message squeezed in 16 char
  // initialize the serial communications:
  Serial.begin(9600);
  Serial.println("Light Sensor LDR voltage values......");//
  delay(1000);// delay of 1 second just for fun.
  
}// end of setup.

void loop() {
  // read the adc count in var i.
  ilight = analogRead(light_sensor_Pin);// note ilight is an int and may have a range of 0 to 1023. 
  flight = 5000.0 * ilight / 1024.0;// voltage in millivolts converted. Decimal point promotes or converts int into float.

  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print("ADC=");// 
  lcd.print(ilight);// show legend and value of ADC count read

  lcd.setCursor(8, 0);// position the cursor on column 8 in top row
  lcd.print("V=");// 
  lcd.print(flight);// show legend and value of voltage read from temperature sensor

  // similarly format a message to be shown on serial monitor in PC
  
  Serial.print("Light sensor LDR ADC count = ");
  Serial.print(ilight);// send legend and value of ADC count read

  Serial.print("  Voltage read in mV =  ");
  Serial.println(flight);// send legend and value of voltage read from light sensor

// All the tasks done. Now waste 1 second before taking next reading.

  delay(1000);
}

  

